# Generated by Django 2.2.9 on 2020-01-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_url', models.CharField(default='ffffffff', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.URLField(blank=True, max_length=2500, unique=True)),
                ('shorten', models.CharField(blank=True, max_length=8, unique=True)),
            ],
        ),
    ]
