# Generated by Django 2.2.9 on 2020-01-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.URLField(max_length=250, null=True, unique=True)),
                ('shorten', models.CharField(max_length=8, null=True, unique=True)),
            ],
        ),
    ]
